parameters:
    ezifttt.content_provider.simple.class: BD\Bundle\EzIFTTTBundle\ContentProvider\Simple

services:
    ezifttt.content_provider:
        alias: ezifttt.content_provider.simple

    ezifttt.content_provider.simple:
        class: %ezifttt.content_provider.simple.class%
        arguments:
            - @ezpublish.api.service.content
            - @ezpublish.api.service.content_type
            - @ezpublish.api.service.location
