parameters:
#    b_de_zifttt.example.class: BD\BDeZIFTTTBundle\Example

services:
#    b_de_zifttt.example:
#        class: %b_de_zifttt.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
