parameters:
    ezifttt.content_provider.simple.class: BD\Bundle\EzIFTTTBundle\ContentProvider\Simple
    ezifttt.ifttt_handler.class: BD\Bundle\EzIFTTTBundle\IFTTT\Handler
    ezifttt.content_provider.id: ezifttt.content_provider.simple
    bdifttt.handler.class: ezifttt.ifttt_handler

services:
    ezifttt.content_provider.simple:
        class: %ezifttt.content_provider.simple.class%
        arguments:
            - @ezpublish.api.service.content
            - @ezpublish.api.service.content_type
            - @ezpublish.api.service.location

    ezifttt.content_provider:
        alias: ezifttt.content_provider.simple

    bdifttt.handler:
        alias: ezifttt.ifttt.handler

    ezifttt.ifttt.handler:
        class: %ezifttt.ifttt_handler.class%
        arguments:
            - @ezpublish.api.repository
            - @ezpublish.api.service.content
            - @ezpublish.api.service.user
            - @ezifttt.content_provider